apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "jenkins.clusterRole" . }}
  labels:
    {{- include "jenkins.commonLabels" . | nindent 4 }}
rules:
  {{- with .Values.rbac.rules }}
  {{- toYaml . | nindent 2 }}
  {{ else }}
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
  {{- end }}
