apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "jenkins.serviceAccountName" . }}
  namespace: {{ template "jenkins.namespace" . }}
  labels:
    {{- include "jenkins.commonLabels" . | nindent 4 }}
