apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "jenkins.serviceAccountName" . }}
  namespace: {{ template "jenkins.namespace" . }}
  annotations: 
    {{- include "jenkins.commonAnnotations" . | nindent 4 }}
  labels:
    {{- include "jenkins.commonLabels" . | nindent 4 }}
