apiVersion: v1
kind: Pod
metadata:
  labels: 
    subtype: django-build
spec:
  containers:
  - name: python
    image: python:3.8
    envFrom:
    - configMapRef:
        name: django-test-env
    tty: true
  - name: db
    image: postgres:9.6.16-alpine
    ports:
    - containerPort: 5432
    tty: true



