apiVersion: v1
kind: ConfigMap
metadata:
  name: django-test-env
  namespace: jenkins-ci
data:
  APP_ENVIRONMENT: local
  DEBUG: "true"
  ENABLE_DEBUG_TOOLBAR: "false"
  ENABLE_SENTRY_REPORTING: "false"
  DJANGO_SECRET_KEY: secret_key
  DATABASE_URL: psql://django:test@127.0.0.1:5432/django
  DJANGO_SITE_URL: http://localhost:9000
  DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
  FRONTEND_APP_URL: http://localhost:4200
  RABBITMQ_USERNAME: guest
  RABBITMQ_PASSWORD: guest
  RABBITMQ_HOST: rabbitmq
