apiVersion: v1
kind: Pod
metadata:
  labels: 
    subtype: reports-build
spec:
  containers:
  - name: sbt
    image: sbtscala/scala-sbt:eclipse-temurin-focal-11.0.17_8_1.8.2_2.13.10
    tty: true
    volumeMounts:
    - name: nexus-creds
      mountPath: /root/.ivy2
      readOnly: true
    - name: storage
      mountPath: /home/jenkins/
      readOnly: false
    - name: temp
      mountPath: /tmp/shared/
      readOnly: false
  volumes:
  - name: nexus-creds
    secret:
      secretName: nexus-ivy-credentials
  - name: temp
    emptyDir:
      sizeLimit: 2Gi
