apiVersion: v1
kind: Pod
metadata:
  labels: 
    subtype: front-build
spec:
  containers:
  - name: node
    image: node:20.10.0-alpine
    volumeMounts:
    - name: storage
      mountPath: /home/jenkins/
      readOnly: false
    tty: true
